SASL & TLS support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -977,6 +977,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-ssl=DIR          path to ssl
+  --with-sasl=DIR         path to sasl
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
 
@@ -2640,6 +2641,45 @@ fi
 
 fi
 
+    echo "$as_me:$LINENO: checking for sasl" >&5
+echo $ECHO_N "checking for sasl... $ECHO_C" >&6
+    sasldirs="/usr/local/sasl2 /usr/lib/sasl2 /usr/sasl2 \
+            /usr/pkg /usr/local /usr"
+
+# Check whether --with-sasl or --without-sasl was given.
+if test "${with_sasl+set}" = set; then
+  withval="$with_sasl"
+  sasldirs="$withval"
+fi;
+    for dir in $sasldirs; do
+        sasldir="$dir"
+        if test -f "$dir/include/sasl/sasl.h"; then
+            found_sasl="yes";
+            CPPFLAGS="$CPPFLAGS -I$sasldir/include";
+            break;
+        fi
+        if test -f "$dir/include/sasl.h"; then
+            found_sasl="yes";
+            CPPFLAGS="$CPPFLAGS -I$sasldir/include";
+            break
+        fi
+    done
+    if test x_$found_sasl != x_yes; then
+        { { echo "$as_me:$LINENO: error: cannot find sasl libraries" >&5
+echo "$as_me: error: cannot find sasl libraries" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+        cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBSASL 1
+_ACEOF
+
+        LIBS="$LIBS -lsasl2";
+        LDFLAGS="$LDFLAGS -L$sasldir/lib";
+    fi
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
 # Checks for header files.
 #AC_HEADER_STDC
 #AC_CHECK_HEADERS([fcntl.h inttypes.h netinet/in.h stdlib.h string.h sys/param.h sys/time.h unistd.h])
@@ -3816,7 +3856,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3819 "configure"' > conftest.$ac_ext
+  echo '#line 3859 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4359,7 +4399,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4362: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4402: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6229,7 +6269,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6232 "configure"
+#line 6272 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6327,7 +6367,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6330 "configure"
+#line 6370 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
